// =================================================================================
// This is auto-generated by Fine CLI tool only once. Fill this file as you wish.
// Created at 2024/10/30 17:40:53.198.
// =================================================================================

package food

import (
	"github.com/gin-gonic/gin"

	"github.com/ZYallers/fine-example/api/product/food"
)

//	@Summary	product/food/page_list
//	@Tags		product
//	@Accept		json
//	@Produce	json
//	@Router		/product/food/page/list [post]
//	@Param		params	body		food.PageListReq	true	"..."
//	@Success	200		{object}	f.JsonResult{data=food.PageListRes}
func (c *cFood) PageList(ctx *gin.Context, req *food.PageListReq) (res *food.PageListRes, err error) {
	return
}
