// =================================================================================
// This is auto-generated by Fine CLI tool only once. Fill this file as you wish.
// Created at 2024/10/30 17:40:53.198.
// =================================================================================

package food

import (
	"github.com/gin-gonic/gin"

	"github.com/ZYallers/fine-example/api/product/food"
)

//	@Summary	product/food/add
//	@Tags		product
//	@Accept		json
//	@Produce	json
//	@Router		/product/food/add [post]
//	@Param		params	body		food.AddReq	true	"..."
//	@Success	200		{object}	f.JsonResult{data=food.AddRes}
func (c *cFood) Add(ctx *gin.Context, req *food.AddReq) (res *food.AddRes, err error) {
	return
}
