// =================================================================================
// This is auto-generated by Fine CLI tool only once. Fill this file as you wish.
// Created at 2024/10/30 17:40:53.198.
// =================================================================================

package device

import (
	"time"

	"github.com/ZYallers/fine-example/api/product/device"
	"github.com/ZYallers/fine-example/internal/consts"
	"github.com/gin-gonic/gin"
)

//	@Summary	product/device/add
//	@Tags		product
//	@Accept		json
//	@Produce	json
//	@Router		/product/device/add [post]
//	@Param		params	body		device.AddReq	true	"..."
//	@Success	200		{object}	f.JsonResult{data=device.AddRes}
func (c *cDevice) Add(ctx *gin.Context, req *device.AddReq) (res *device.AddRes, err error) {
	res = new(device.AddRes)
	res.Req = req
	res.Now = time.Now().Format(consts.TimeLogFormat)
	return
}
