// =================================================================================
// This is auto-generated by Fine CLI tool only once. Fill this file as you wish.
// Created at 2024/10/30 17:40:53.198.
// =================================================================================

package device

import (
	"github.com/gin-gonic/gin"

	"github.com/ZYallers/fine-example/api/product/device"
)

//	@Summary	product/device/detail
//	@Tags		product
//	@Accept		json
//	@Produce	json
//	@Router		/product/device/detail [post]
//	@Param		params	body		device.DetailReq	true	"..."
//	@Success	200		{object}	f.JsonResult{data=device.DetailRes}
func (c *cDevice) Detail(ctx *gin.Context, req *device.DetailReq) (res *device.DetailRes, err error) {
	res = &device.DetailRes{}
	return
}
