// =================================================================================
// This is auto-generated by Fine CLI tool only once. Fill this file as you wish.
// Created at 2024/10/30 17:40:53.202.
// =================================================================================

package student

import (
	"github.com/gin-gonic/gin"

	"github.com/ZYallers/fine-example/api/school/student"
)

//	@Summary	school/student/add
//	@Tags		school
//	@Accept		json
//	@Produce	json
//	@Router		/school/student/add [post]
//	@Param		params	body		student.AddReq	true	"..."
//	@Success	200		{object}	f.JsonResult{data=student.AddRes}
func (c *cStudent) Add(ctx *gin.Context, req *student.AddReq) (res *student.AddRes, err error) {
	return
}
